// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCesa1zNeuzn1mgJhhI6myACX8fmARK5T0',
    appId: '1:548979390930:web:d5c3f8799d86de324ef00b',
    messagingSenderId: '548979390930',
    projectId: 'theraputico-cc096',
    authDomain: 'theraputico-cc096.firebaseapp.com',
    storageBucket: 'theraputico-cc096.appspot.com',
    measurementId: 'G-7F47TGMC5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFedeJP02Dqu91JI_a5Aw-yXE97z8GhS8',
    appId: '1:548979390930:android:6adcedd6898671a84ef00b',
    messagingSenderId: '548979390930',
    projectId: 'theraputico-cc096',
    storageBucket: 'theraputico-cc096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz3COTDyf0lQSBF0iN3fjnYjfqwrSQ6aY',
    appId: '1:548979390930:ios:9d39139f026b1c2b4ef00b',
    messagingSenderId: '548979390930',
    projectId: 'theraputico-cc096',
    storageBucket: 'theraputico-cc096.appspot.com',
    iosBundleId: 'com.example.medsearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz3COTDyf0lQSBF0iN3fjnYjfqwrSQ6aY',
    appId: '1:548979390930:ios:cc5905d53d7e7fde4ef00b',
    messagingSenderId: '548979390930',
    projectId: 'theraputico-cc096',
    storageBucket: 'theraputico-cc096.appspot.com',
    iosBundleId: 'com.example.medsearch.RunnerTests',
  );
}
